'use client';
import { useMemo, useState } from 'react';

type Product = { id:string; name:string; description:string; category:'Footwear'|'Apparel'|'Accessories'|'Equipment'; price:number; keyword:number; vector:number; x:number; y:number; color:string };
const products:Product[] = [
  {id:'PRD-4821',name:'TerraRun Pro',description:'Trail running shoes with responsive foam and a grippy all-terrain outsole.',category:'Footwear',price:149,keyword:96,vector:92,x:25,y:25,color:'#ff7048'},
  {id:'PRD-2674',name:'CloudStep Lite',description:'Ultra-light road runners engineered for daily miles and soft landings.',category:'Footwear',price:119,keyword:91,vector:89,x:34,y:37,color:'#ff7048'},
  {id:'PRD-8103',name:'Summit Trek GTX',description:'Waterproof hiking shoes with a stable heel and rugged traction.',category:'Footwear',price:179,keyword:82,vector:94,x:20,y:43,color:'#ff7048'},
  {id:'PRD-3391',name:'PaceKnit Trainer',description:'Breathable knit trainers for tempo sessions and everyday movement.',category:'Footwear',price:99,keyword:88,vector:83,x:42,y:26,color:'#ff7048'},
  {id:'PRD-5902',name:'AeroShell Jacket',description:'Packable wind shell with laser-cut ventilation and a water-resistant finish.',category:'Apparel',price:129,keyword:48,vector:70,x:69,y:28,color:'#1d9b85'},
  {id:'PRD-1266',name:'MotionFlex Tee',description:'Quick-drying performance tee made from soft recycled fibers.',category:'Apparel',price:45,keyword:42,vector:62,x:75,y:42,color:'#1d9b85'},
  {id:'PRD-7720',name:'TrailCore Pack',description:'A stable 12-liter hydration pack built for long trail days.',category:'Accessories',price:89,keyword:53,vector:76,x:58,y:66,color:'#627eea'},
  {id:'PRD-4459',name:'Pulse GPS Watch',description:'Multisport GPS watch with training readiness and route guidance.',category:'Accessories',price:299,keyword:36,vector:57,x:72,y:72,color:'#627eea'},
  {id:'PRD-9014',name:'FlexRoll Pro',description:'Textured recovery roller for mobility work and post-run release.',category:'Equipment',price:39,keyword:31,vector:51,x:45,y:76,color:'#c68428'},
  {id:'PRD-6037',name:'Stride Poles',description:'Carbon trekking poles with cork grips and quick-lock adjustment.',category:'Equipment',price:139,keyword:45,vector:68,x:32,y:67,color:'#c68428'},
];
const categories = ['All categories','Footwear','Apparel','Accessories','Equipment'] as const;

export default function Home(){
  const [query,setQuery]=useState('lightweight trail running shoes'); const [category,setCategory]=useState<(typeof categories)[number]>('Footwear'); const [keywordWeight,setKeywordWeight]=useState(40); const [selected,setSelected]=useState(products[0].id); const [searched,setSearched]=useState(true);
  const results=useMemo(()=>products.filter(p=>category==='All categories'||p.category===category).map(p=>({...p,score:Math.round((p.keyword*keywordWeight+p.vector*(100-keywordWeight))/100)})).sort((a,b)=>b.score-a.score),[category,keywordWeight]);
  const active=products.find(p=>p.id===selected)??products[0];
  const runSearch=()=>{setSearched(false);window.setTimeout(()=>{setSearched(true);if(results[0])setSelected(results[0].id)},420)};
  return <main>
    <header className="topbar"><a className="brand" href="#"><span className="brandmark">V</span><span>VectorScope</span></a><div className="header-actions"><span className="live"><i/> COLLECTION LIVE</span><button className="icon-button" aria-label="Settings">⚙</button><span className="avatar">AK</span></div></header>
    <section className="intro"><div><p className="eyebrow">SEARCH WORKBENCH <span>•</span> PRODUCTS_V3</p><h1>Hybrid search, <em>made visible.</em></h1><p className="subtitle">Blend lexical precision with semantic understanding. Filter by metadata, tune the weights, and see how every result earns its rank.</p></div><div className="stats"><div><b>10K</b><span>VECTORS</span></div><div><b>384</b><span>DIMENSIONS</span></div><div><b>12ms</b><span>AVG. LATENCY</span></div></div></section>
    <section className="workbench">
      <aside className="controls"><div className="panel-title"><span>01</span><div><h2>Search controls</h2><p>Shape your retrieval query</p></div></div><label>QUERY</label><div className="query-box"><span>⌕</span><textarea value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search query"/><kbd>⌘ ↵</kbd></div><label>PRODUCT CATEGORY <span className="optional">METADATA FILTER</span></label><select value={category} onChange={e=>setCategory(e.target.value as typeof category)}>{categories.map(c=><option key={c}>{c}</option>)}</select><div className="filter-note"><span>◆</span><p><b>WHERE</b> category = “{category}”</p></div><div className="weight-head"><label>SEARCH BLEND</label><span>{keywordWeight}% / {100-keywordWeight}%</span></div><div className="blend-labels"><span>Keyword</span><span>Semantic</span></div><input className="range" type="range" min="0" max="100" value={keywordWeight} onChange={e=>setKeywordWeight(Number(e.target.value))} style={{'--pos':`${keywordWeight}%`} as React.CSSProperties}/><div className="blend-labels muted"><span>BM25</span><span>Cosine similarity</span></div><button className="search-button" onClick={runSearch}><span>⌕</span>{searched?'Run hybrid search':'Searching…'}<kbd>⌘ ↵</kbd></button><p className="tech">Powered by <b>ChromaDB</b> <span>×</span> <b>LangChain</b></p></aside>
      <section className="results-panel"><div className="panel-title"><span>02</span><div><h2>Ranked results</h2><p>{results.length} matches in 12ms</p></div><button>↥ Export</button></div><div className={`results ${searched?'':'loading'}`}>{results.map((p,i)=><article key={p.id} onClick={()=>setSelected(p.id)} className={selected===p.id?'selected':''}><div className="rank">{String(i+1).padStart(2,'0')}</div><div className="result-body"><div className="result-top"><span className="category-dot" style={{background:p.color}}/><h3>{p.name}</h3><span className="tag">{p.category}</span><b>${p.price}</b></div><p>{p.description}</p><div className="result-meta"><code>{p.id}</code><span>KEYWORD <b>{p.keyword/100}</b></span><span>VECTOR <b>{p.vector/100}</b></span></div></div><div className="score"><strong>{p.score}</strong><span>SCORE</span></div></article>)}</div></section>
      <aside className="map-panel"><div className="panel-title"><span>03</span><div><h2>Vector space</h2><p>2D UMAP projection</p></div><button>⛶</button></div><div className="map" aria-label="Vector store visualization"><div className="grid-lines"/>{products.map(p=><button key={p.id} className={`point ${selected===p.id?'active':''}`} style={{left:`${p.x}%`,top:`${p.y}%`,background:p.color}} onClick={()=>setSelected(p.id)} aria-label={`Select ${p.name}`}/>)}<div className="query-point" style={{left:'29%',top:'31%'}}><i/><span>QUERY VECTOR</span></div></div><div className="legend"><span><i style={{background:'#ff7048'}}/>Footwear</span><span><i style={{background:'#1d9b85'}}/>Apparel</span><span><i style={{background:'#627eea'}}/>Accessories</span><span><i style={{background:'#c68428'}}/>Equipment</span></div><div className="selected-card"><p>SELECTED VECTOR</p><div><span className="category-dot" style={{background:active.color}}/><h3>{active.name}</h3><b>{active.id}</b></div><dl><div><dt>Cosine distance</dt><dd>{(1-active.vector/100).toFixed(3)}</dd></div><div><dt>Nearest neighbors</dt><dd>8</dd></div><div><dt>Category</dt><dd>{active.category}</dd></div></dl></div><p className="map-tip">Select any point to inspect its metadata and similarity.</p></aside>
    </section>
  </main>
}
